version: "2"
services:
  server:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - 8083:8080
    volumes:
      - ./code:/home/coder/project
      - /home/coder/project/vendor
    environment:
      - PORT=8080
      - PASSWORD=test
